
services:

  eventstore:
    image: kurrentplatform/kurrentdb:25.1
    environment:
      - KURRENTDB_CLUSTER_SIZE=1
      - KURRENTDB_RUN_PROJECTIONS=All
      - KURRENTDB_START_STANDARD_PROJECTIONS=true
      - KURRENTDB_NODE_PORT=2113
      - KURRENTDB_INSECURE=true
      - KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
    volumes:
      - type: volume
        source: kurrent-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: kurrent-volume-logs
        target: /var/log/eventstore
    networks:
      - common_net

  redis:
    image: redis:7.2.4-bookworm
    ports:
      - "6379:6379"
    networks:
      - common_net

volumes:
  kurrent-volume-data:
  kurrent-volume-logs:

networks:
  common_net:
    external: true
    name: common_network
